# clean-env.ps1 - "Spin up clean instance" for the OpenHarness QA harness.
#
# Triggered on demand from the web UI (Run page -> "Spin up clean instance"), which
# POSTs to /api/setup/run and executes this file via:
#   pwsh -NoProfile -ExecutionPolicy Bypass -File TestAgent/clean-env.ps1
# stdout/stderr stream live to the UI and the exit code is surfaced; non-zero = failure.
#
# What it does, in order:
#   1. Stop any running Unreal Editor (so QAActive isn't file-locked during the copy).
#   2. git pull the latest VibeUE plugin inside the CLEAN project.
#   3. Mirror the clean project -> active project (wipes whatever was in QAActive first),
#      skipping regenerable/lock-prone build artifacts (Intermediate, Binaries,
#      DerivedDataCache, Saved, .git) so the copy is fast and never trips on locked DLLs.
#   4. Run VibeUE's BuildAndLaunchGame.ps1 from the ACTIVE project (builds + launches editor).
#
# A lock file prevents two runs from colliding (a second run while a build is still writing
# QAActive is what causes robocopy "exit 8 / files in use" failures).
#
# Paths default to the repo layout (QAClean / QAActive as siblings of this repo) but can
# be overridden.

param(
    # The known-good, clean Unreal project that is the source of truth.
    # (Agents\VibeUE-Unreal -> ..\..\.. is the repo's parent, i.e. E:\Repo)
    [string]$CleanProject = (Join-Path $PSScriptRoot "..\..\..\QAClean"),
    # The throwaway working copy that tests actually run against.
    [string]$ActiveProject = (Join-Path $PSScriptRoot "..\..\..\QAActive"),
    # VibeUE plugin location within a project (also where BuildAndLaunchGame.ps1 lives).
    [string]$PluginSubPath = "Plugins\VibeUE",
    # Folders to skip when mirroring: build artifacts and caches that are regenerated by
    # step 4's build (or the editor), and that are frequently locked by build tooling
    # (UnrealBuildTool keeps Intermediate\Build\BuildRules\*.dll and Binaries\*.dll open),
    # which would otherwise make robocopy fail with "files in use" (exit >= 8). Skipping them
    # means step 4 does a clean build (correct for a "clean instance"; slower than incremental).
    # Pass @() for a full byte-for-byte copy.
    [string[]]$ExcludeDirs = @("Intermediate", "Binaries", "DerivedDataCache", "Saved", ".git", ".vs"),
    # By default the build runs with BuildAndLaunchGame.ps1 -StrictRebuild, which wipes the
    # (freshly git-pulled) VibeUE plugin's Binaries/Intermediate so it is cleanly recompiled -
    # correct for a clean instance, since the plugin is the thing under test. Pass
    # -NoStrictRebuild for a faster incremental build.
    [switch]$NoStrictRebuild
)

$ErrorActionPreference = "Stop"

function Resolve-FullPath([string]$path) { [System.IO.Path]::GetFullPath($path) }

$CleanProject  = Resolve-FullPath $CleanProject
$ActiveProject = Resolve-FullPath $ActiveProject
$cleanPlugin   = Join-Path $CleanProject  $PluginSubPath
$activePlugin  = Join-Path $ActiveProject $PluginSubPath
$buildScript   = Join-Path $activePlugin "BuildAndLaunchGame.ps1"

Write-Host "=== Spin up clean instance ===" -ForegroundColor Cyan
Write-Host "Clean project  : $CleanProject"
Write-Host "Active project : $ActiveProject"

if (-not (Test-Path $CleanProject)) { throw "Clean project not found: $CleanProject" }
if (-not (Test-Path $cleanPlugin))  { throw "VibeUE plugin not found in clean project: $cleanPlugin" }

# ----------------------------------------------------------------------------
# Concurrency guard - refuse to run while another spin-up is still in progress
# (a build writing QAActive locks files and makes the mirror fail).
# ----------------------------------------------------------------------------
$lockFile = Join-Path ([System.IO.Path]::GetTempPath()) "openharness-clean-env.lock"
if (Test-Path $lockFile) {
    $ageMin = [int]((Get-Date) - (Get-Item $lockFile).LastWriteTime).TotalMinutes
    if ($ageMin -lt 60) {
        throw "Another 'spin up clean instance' run looks active (lock $lockFile, ${ageMin}m old). Wait for it to finish, or delete that file to override."
    }
    Write-Host "Clearing stale lock ($ageMin min old)." -ForegroundColor Gray
}
Set-Content -Path $lockFile -Value (Get-Date -Format o)

try {
    # ------------------------------------------------------------------------
    # 1. Stop any running Unreal Editor so QAActive's files aren't locked.
    # ------------------------------------------------------------------------
    Write-Host "`n[1/4] Stopping any running Unreal Editor..." -ForegroundColor Yellow
    $getUnreal = { Get-Process -ErrorAction SilentlyContinue | Where-Object {
        $_.ProcessName -like "UnrealEditor*" -or $_.ProcessName -like "CrashReportClient*" -or $_.ProcessName -eq "UnrealTraceServer"
    } }
    $procs = & $getUnreal
    if ($procs) {
        $procs | ForEach-Object { if ($_.MainWindowHandle -ne 0) { $_.CloseMainWindow() | Out-Null } }
        $elapsed = 0
        while ((& $getUnreal) -and ($elapsed -lt 15)) { Start-Sleep 1; $elapsed++ }
        $remaining = & $getUnreal
        if ($remaining) {
            Write-Host "  Forcing shutdown..." -ForegroundColor Gray
            $remaining | ForEach-Object { taskkill /F /PID $_.Id /T 2>$null | Out-Null }
            Start-Sleep 2
        }
        Write-Host "  Unreal Editor stopped." -ForegroundColor Green
    } else {
        Write-Host "  No running Unreal Editor found." -ForegroundColor Gray
    }

    # ------------------------------------------------------------------------
    # 2. Pull the latest VibeUE plugin in the CLEAN project.
    # ------------------------------------------------------------------------
    Write-Host "`n[2/4] Pulling latest VibeUE ($cleanPlugin)..." -ForegroundColor Yellow
    git -C $cleanPlugin pull
    if ($LASTEXITCODE -ne 0) { throw "git pull failed in $cleanPlugin (exit $LASTEXITCODE)." }

    # ------------------------------------------------------------------------
    # 3. Mirror clean -> active. /MIR makes QAActive identical to QAClean (wipe-then-copy),
    #    minus $ExcludeDirs. robocopy exit codes are bit flags: 0-7 = success
    #    (1=copied, 2=extras removed, 4=mismatch), >=8 = real copy errors.
    # ------------------------------------------------------------------------
    Write-Host "`n[3/4] Refreshing active project from clean copy..." -ForegroundColor Yellow
    if ($ExcludeDirs.Count) { Write-Host "  Skipping: $($ExcludeDirs -join ', ')" -ForegroundColor Gray }
    New-Item -ItemType Directory -Force -Path $ActiveProject | Out-Null
    $roboArgs = @($CleanProject, $ActiveProject, "/MIR")
    if ($ExcludeDirs.Count) { $roboArgs += "/XD"; $roboArgs += $ExcludeDirs }
    $roboArgs += @("/NFL", "/NDL", "/NJH", "/NJS", "/NP", "/R:2", "/W:2")
    robocopy @roboArgs | Out-Null
    $roboCode = $LASTEXITCODE
    if ($roboCode -ge 8) {
        throw "robocopy mirror failed (exit $roboCode). The 8-or-higher code means files were in use/locked - close the editor or any build using $ActiveProject and retry."
    }
    $global:LASTEXITCODE = 0
    Write-Host "  Active project ready: $ActiveProject" -ForegroundColor Green

    # ------------------------------------------------------------------------
    # 4. Build + launch the active project via VibeUE's own script.
    #    (It walks up to find the .uproject, stops editors again, builds, launches.)
    # ------------------------------------------------------------------------
    Write-Host "`n[4/4] Building and launching active project..." -ForegroundColor Yellow
    if (-not (Test-Path $buildScript)) { throw "Build script not found: $buildScript" }
    if ($NoStrictRebuild) { & $buildScript } else { & $buildScript -StrictRebuild }
    if ($LASTEXITCODE -ne 0) { throw "BuildAndLaunchGame.ps1 failed (exit $LASTEXITCODE)." }

    Write-Host "`n=== Clean instance ready ===" -ForegroundColor Green
}
finally {
    Remove-Item -Path $lockFile -Force -ErrorAction SilentlyContinue
}

exit 0
